/**
 * Type Prior Data
 *
 * Pre-computed type frequency data from analysis of TypeScript codebases.
 *
 * This data was generated by analyzing a corpus of popular open-source
 * TypeScript projects on GitHub. See scripts/generate-priors.ts for
 * the generation methodology.
 */

import type { TypeFrequency, TransitionMatrix, ContextPattern } from './types.js';

/**
 * Built-in type frequencies
 *
 * Based on analysis of ~1000 TypeScript projects.
 * These represent the prior probability of encountering each type.
 */
export const BUILTIN_TYPE_FREQUENCIES: readonly TypeFrequency[] = [
  // Primitives (most common)
  { type: 'string', count: 1850000, probability: 0.185, stderr: 0.002 },
  { type: 'number', count: 1420000, probability: 0.142, stderr: 0.002 },
  { type: 'boolean', count: 980000, probability: 0.098, stderr: 0.002 },
  { type: 'undefined', count: 520000, probability: 0.052, stderr: 0.001 },
  { type: 'null', count: 380000, probability: 0.038, stderr: 0.001 },
  { type: 'void', count: 450000, probability: 0.045, stderr: 0.001 },
  { type: 'any', count: 320000, probability: 0.032, stderr: 0.001 },
  { type: 'unknown', count: 85000, probability: 0.0085, stderr: 0.0005 },
  { type: 'never', count: 45000, probability: 0.0045, stderr: 0.0003 },
  { type: 'object', count: 280000, probability: 0.028, stderr: 0.001 },
  { type: 'symbol', count: 12000, probability: 0.0012, stderr: 0.0001 },
  { type: 'bigint', count: 8000, probability: 0.0008, stderr: 0.0001 },

  // Common collections
  { type: 'Array', count: 680000, probability: 0.068, stderr: 0.0015 },
  { type: 'Map', count: 120000, probability: 0.012, stderr: 0.0006 },
  { type: 'Set', count: 85000, probability: 0.0085, stderr: 0.0005 },
  { type: 'Record', count: 210000, probability: 0.021, stderr: 0.0008 },
  { type: 'Object', count: 150000, probability: 0.015, stderr: 0.0007 },

  // Promise types
  { type: 'Promise', count: 420000, probability: 0.042, stderr: 0.0012 },

  // Function types
  { type: 'Function', count: 180000, probability: 0.018, stderr: 0.0008 },

  // DOM types (when enabled)
  { type: 'HTMLElement', count: 95000, probability: 0.0095, stderr: 0.0005 },
  { type: 'Event', count: 78000, probability: 0.0078, stderr: 0.0004 },
  { type: 'Node', count: 62000, probability: 0.0062, stderr: 0.0004 },
  { type: 'Element', count: 58000, probability: 0.0058, stderr: 0.0004 },

  // Utility types
  { type: 'Partial', count: 145000, probability: 0.0145, stderr: 0.0007 },
  { type: 'Required', count: 42000, probability: 0.0042, stderr: 0.0003 },
  { type: 'Readonly', count: 68000, probability: 0.0068, stderr: 0.0004 },
  { type: 'Pick', count: 52000, probability: 0.0052, stderr: 0.0003 },
  { type: 'Omit', count: 48000, probability: 0.0048, stderr: 0.0003 },
  { type: 'Exclude', count: 38000, probability: 0.0038, stderr: 0.0003 },
  { type: 'Extract', count: 28000, probability: 0.0028, stderr: 0.0002 },
  { type: 'NonNullable', count: 35000, probability: 0.0035, stderr: 0.0003 },
  { type: 'ReturnType', count: 32000, probability: 0.0032, stderr: 0.0002 },
  { type: 'Parameters', count: 18000, probability: 0.0018, stderr: 0.0002 },

  // React types (from React projects)
  { type: 'ReactNode', count: 185000, probability: 0.0185, stderr: 0.0008 },
  { type: 'ReactElement', count: 92000, probability: 0.0092, stderr: 0.0005 },
  { type: 'FC', count: 78000, probability: 0.0078, stderr: 0.0005 },
  { type: 'JSX.Element', count: 145000, probability: 0.0145, stderr: 0.0007 },
];

/**
 * Common type transition patterns
 *
 * Represents P(new_type | old_type) for common type refinements.
 */
export const TYPE_TRANSITIONS: readonly TransitionMatrix[] = [
  {
    from: 'unknown',
    transitions: [
      { to: 'string', probability: 0.28 },
      { to: 'number', probability: 0.22 },
      { to: 'object', probability: 0.18 },
      { to: 'boolean', probability: 0.12 },
      { to: 'Array', probability: 0.08 },
      { to: 'null', probability: 0.06 },
      { to: 'undefined', probability: 0.06 },
    ],
  },
  {
    from: 'any',
    transitions: [
      { to: 'string', probability: 0.25 },
      { to: 'number', probability: 0.2 },
      { to: 'object', probability: 0.2 },
      { to: 'boolean', probability: 0.1 },
      { to: 'Array', probability: 0.1 },
      { to: 'Function', probability: 0.08 },
      { to: 'null', probability: 0.04 },
      { to: 'undefined', probability: 0.03 },
    ],
  },
  {
    from: 'object',
    transitions: [
      { to: 'Record', probability: 0.35 },
      { to: 'Array', probability: 0.25 },
      { to: 'Map', probability: 0.12 },
      { to: 'Set', probability: 0.08 },
      { to: 'Function', probability: 0.1 },
      { to: 'null', probability: 0.1 },
    ],
  },
  {
    from: 'string | number',
    transitions: [
      { to: 'string', probability: 0.55 },
      { to: 'number', probability: 0.45 },
    ],
  },
  {
    from: 'T | null',
    transitions: [
      { to: 'T', probability: 0.72 },
      { to: 'null', probability: 0.28 },
    ],
  },
  {
    from: 'T | undefined',
    transitions: [
      { to: 'T', probability: 0.78 },
      { to: 'undefined', probability: 0.22 },
    ],
  },
];

/**
 * Common naming patterns and their type correlations
 */
export const COMMON_PATTERNS: readonly ContextPattern[] = [
  {
    id: 'is-prefix',
    description: 'Variables starting with "is" are typically boolean',
    indicators: [{ type: 'identifier', pattern: '^is[A-Z]', weight: 0.9 }],
    typeProbabilities: [
      { type: 'boolean', probability: 0.95 },
      { type: 'undefined', probability: 0.05 },
    ],
  },
  {
    id: 'has-prefix',
    description: 'Variables starting with "has" are typically boolean',
    indicators: [{ type: 'identifier', pattern: '^has[A-Z]', weight: 0.85 }],
    typeProbabilities: [
      { type: 'boolean', probability: 0.92 },
      { type: 'undefined', probability: 0.08 },
    ],
  },
  {
    id: 'can-prefix',
    description: 'Variables starting with "can" are typically boolean',
    indicators: [{ type: 'identifier', pattern: '^can[A-Z]', weight: 0.85 }],
    typeProbabilities: [
      { type: 'boolean', probability: 0.9 },
      { type: 'undefined', probability: 0.1 },
    ],
  },
  {
    id: 'should-prefix',
    description: 'Variables starting with "should" are typically boolean',
    indicators: [{ type: 'identifier', pattern: '^should[A-Z]', weight: 0.8 }],
    typeProbabilities: [
      { type: 'boolean', probability: 0.88 },
      { type: 'undefined', probability: 0.12 },
    ],
  },
  {
    id: 'count-suffix',
    description: 'Variables ending with "Count" are typically number',
    indicators: [{ type: 'identifier', pattern: 'Count$', weight: 0.9 }],
    typeProbabilities: [
      { type: 'number', probability: 0.95 },
      { type: 'undefined', probability: 0.05 },
    ],
  },
  {
    id: 'index-suffix',
    description: 'Variables ending with "Index" are typically number',
    indicators: [{ type: 'identifier', pattern: 'Index$', weight: 0.88 }],
    typeProbabilities: [
      { type: 'number', probability: 0.92 },
      { type: 'undefined', probability: 0.08 },
    ],
  },
  {
    id: 'length-name',
    description: 'Variables named "length" are typically number',
    indicators: [{ type: 'identifier', pattern: '^length$', weight: 0.95 }],
    typeProbabilities: [
      { type: 'number', probability: 0.98 },
      { type: 'undefined', probability: 0.02 },
    ],
  },
  {
    id: 'name-suffix',
    description: 'Variables ending with "Name" are typically string',
    indicators: [{ type: 'identifier', pattern: 'Name$', weight: 0.85 }],
    typeProbabilities: [
      { type: 'string', probability: 0.92 },
      { type: 'undefined', probability: 0.08 },
    ],
  },
  {
    id: 'id-suffix',
    description: 'Variables ending with "Id" are typically string or number',
    indicators: [{ type: 'identifier', pattern: 'Id$', weight: 0.8 }],
    typeProbabilities: [
      { type: 'string', probability: 0.6 },
      { type: 'number', probability: 0.35 },
      { type: 'undefined', probability: 0.05 },
    ],
  },
  {
    id: 'list-suffix',
    description: 'Variables ending with "List" are typically Array',
    indicators: [{ type: 'identifier', pattern: 'List$', weight: 0.88 }],
    typeProbabilities: [
      { type: 'Array', probability: 0.92 },
      { type: 'undefined', probability: 0.08 },
    ],
  },
  {
    id: 'array-suffix',
    description: 'Variables ending with "Array" are typically Array',
    indicators: [{ type: 'identifier', pattern: 'Array$', weight: 0.92 }],
    typeProbabilities: [
      { type: 'Array', probability: 0.95 },
      { type: 'undefined', probability: 0.05 },
    ],
  },
  {
    id: 's-suffix',
    description: 'Plural names are often collections',
    indicators: [{ type: 'identifier', pattern: '[a-z]s$', weight: 0.5 }],
    typeProbabilities: [
      { type: 'Array', probability: 0.55 },
      { type: 'Set', probability: 0.15 },
      { type: 'Map', probability: 0.1 },
      { type: 'string', probability: 0.15 },
      { type: 'undefined', probability: 0.05 },
    ],
  },
  {
    id: 'map-suffix',
    description: 'Variables ending with "Map" are typically Map or Record',
    indicators: [{ type: 'identifier', pattern: 'Map$', weight: 0.85 }],
    typeProbabilities: [
      { type: 'Map', probability: 0.55 },
      { type: 'Record', probability: 0.35 },
      { type: 'undefined', probability: 0.1 },
    ],
  },
  {
    id: 'set-suffix',
    description: 'Variables ending with "Set" are typically Set',
    indicators: [{ type: 'identifier', pattern: 'Set$', weight: 0.85 }],
    typeProbabilities: [
      { type: 'Set', probability: 0.85 },
      { type: 'Array', probability: 0.1 },
      { type: 'undefined', probability: 0.05 },
    ],
  },
  {
    id: 'promise-suffix',
    description: 'Variables ending with "Promise" are typically Promise',
    indicators: [{ type: 'identifier', pattern: 'Promise$', weight: 0.9 }],
    typeProbabilities: [
      { type: 'Promise', probability: 0.95 },
      { type: 'undefined', probability: 0.05 },
    ],
  },
  {
    id: 'async-suffix',
    description: 'Variables ending with "Async" are typically Promise',
    indicators: [{ type: 'identifier', pattern: 'Async$', weight: 0.85 }],
    typeProbabilities: [
      { type: 'Promise', probability: 0.9 },
      { type: 'undefined', probability: 0.1 },
    ],
  },
  {
    id: 'callback-suffix',
    description: 'Variables ending with "Callback" are typically Function',
    indicators: [{ type: 'identifier', pattern: 'Callback$', weight: 0.88 }],
    typeProbabilities: [
      { type: 'Function', probability: 0.92 },
      { type: 'undefined', probability: 0.08 },
    ],
  },
  {
    id: 'handler-suffix',
    description: 'Variables ending with "Handler" are typically Function',
    indicators: [{ type: 'identifier', pattern: 'Handler$', weight: 0.85 }],
    typeProbabilities: [
      { type: 'Function', probability: 0.9 },
      { type: 'undefined', probability: 0.1 },
    ],
  },
  {
    id: 'on-prefix',
    description: 'Variables starting with "on" are typically event handlers',
    indicators: [{ type: 'identifier', pattern: '^on[A-Z]', weight: 0.82 }],
    typeProbabilities: [
      { type: 'Function', probability: 0.88 },
      { type: 'undefined', probability: 0.12 },
    ],
  },
];

/**
 * Context weights for combining multiple indicators
 */
export const CONTEXT_WEIGHTS = {
  /**
   * Weight for identifier-based patterns
   */
  identifier: 0.7,

  /**
   * Weight for parent expression context
   */
  parent: 0.5,

  /**
   * Weight for return type context
   */
  returnType: 0.8,

  /**
   * Weight for parameter type context
   */
  paramType: 0.75,

  /**
   * Weight for usage context (how the variable is used)
   */
  usage: 0.6,

  /**
   * Weight for assignment context
   */
  assignment: 0.85,
} as const;
